/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hridaya.tickbill.view;

import com.formdev.flatlaf.FlatClientProperties;
import com.hridaya.tickbill.database.DbConnection;
import com.hridaya.tickbill.session.SessionManager;

import javax.swing.border.Border;
import java.awt.*;
import java.sql.Connection;

/**
 *
 * @author hridaya
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        this.setExtendedState(MainFrame.MAXIMIZED_BOTH);

        checkDbConnectionStatus();
        userAccess();
    }


    private void userAccess() {
        SessionManager.userRoleEnum userRole = SessionManager.getInstance().getUserRole();

        if (userRole != SessionManager.userRoleEnum.ADMIN) {
            showUsersButton.setEnabled(false);
            showProductsButton.setEnabled(false);
        }
    }

    private void checkDbConnectionStatus() {
        Connection conn = DbConnection.getConnection();
        if (conn != null) {
            dbConnectionShowStatusLabel.setText("CONNECTED");
        } else {
            dbConnectionShowStatusLabel.setText("DISCONNECTED");
        }
    }

    JPanelLoader jPanelLoader = new JPanelLoader();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarButtonGroup = new javax.swing.ButtonGroup();
        sidebarPanel = new javax.swing.JPanel();
        showUsersButton = new javax.swing.JToggleButton();
        showProductsButton = new javax.swing.JToggleButton();
        showInvoiceButton = new javax.swing.JToggleButton();
        showSalesButton = new javax.swing.JToggleButton();
        showReportsButton = new javax.swing.JToggleButton();
        exportImportButton = new javax.swing.JToggleButton();
        panelLoader = new javax.swing.JPanel();
        dbConnectionStatusLabel = new javax.swing.JLabel();
        dbConnectionShowStatusLabel = new javax.swing.JLabel();
        terminateSessionButton = new javax.swing.JButton();
        showUserInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sideBarButtonGroup.add(showUsersButton);
        showUsersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showUsersButton.setText("Users");
        showUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUsersButtonActionPerformed(evt);
            }
        });

        sideBarButtonGroup.add(showProductsButton);
        showProductsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showProductsButton.setText("Products");
        showProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProductsButtonActionPerformed(evt);
            }
        });

        sideBarButtonGroup.add(showInvoiceButton);
        showInvoiceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showInvoiceButton.setText("Invoice");
        showInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInvoiceButtonActionPerformed(evt);
            }
        });

        sideBarButtonGroup.add(showSalesButton);
        showSalesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showSalesButton.setText("Sales");
        showSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSalesButtonActionPerformed(evt);
            }
        });

        sideBarButtonGroup.add(showReportsButton);
        showReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showReportsButton.setText("Report");
        showReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportsButtonActionPerformed(evt);
            }
        });

        sideBarButtonGroup.add(exportImportButton);
        exportImportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exportImportButton.setText("Export / Import");
        exportImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportImportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(showProductsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showInvoiceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showSalesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportImportButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showReportsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(showUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(showProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(showInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(showReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(showSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(exportImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        panelLoader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLoader.setMaximumSize(new java.awt.Dimension(1506, 703));
        panelLoader.setMinimumSize(new java.awt.Dimension(1506, 703));
        panelLoader.setPreferredSize(new java.awt.Dimension(1506, 703));

        javax.swing.GroupLayout panelLoaderLayout = new javax.swing.GroupLayout(panelLoader);
        panelLoader.setLayout(panelLoaderLayout);
        panelLoaderLayout.setHorizontalGroup(
            panelLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1502, Short.MAX_VALUE)
        );
        panelLoaderLayout.setVerticalGroup(
            panelLoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dbConnectionStatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dbConnectionStatusLabel.setText("Database Connection Status:");

        dbConnectionShowStatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dbConnectionShowStatusLabel.setText("STATUS");

        terminateSessionButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        terminateSessionButton.setText("Terminate");
        terminateSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminateSessionButtonActionPerformed(evt);
            }
        });

        showUserInfoButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        showUserInfoButton.setText("User Info");
        showUserInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showUserInfoButton)
                        .addGap(18, 18, 18)
                        .addComponent(terminateSessionButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dbConnectionStatusLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dbConnectionShowStatusLabel)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(panelLoader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(terminateSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showUserInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLoader, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbConnectionStatusLabel)
                    .addComponent(dbConnectionShowStatusLabel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProductsButtonActionPerformed
        ProductUI productUI = new ProductUI();
        jPanelLoader.JPanelLoader(panelLoader, productUI);
    }//GEN-LAST:event_showProductsButtonActionPerformed

    private void showInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInvoiceButtonActionPerformed
        InvoiceUI invoiceUI = new InvoiceUI();
        jPanelLoader.JPanelLoader(panelLoader, invoiceUI);
    }//GEN-LAST:event_showInvoiceButtonActionPerformed

    private void showSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSalesButtonActionPerformed
        SaleUI saleUI = new SaleUI();
        jPanelLoader.JPanelLoader(panelLoader, saleUI);
    }//GEN-LAST:event_showSalesButtonActionPerformed

    private void showUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUsersButtonActionPerformed
        UserUI userUI = new UserUI();
        jPanelLoader.JPanelLoader(panelLoader, userUI);
    }//GEN-LAST:event_showUsersButtonActionPerformed

    private void showReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportsButtonActionPerformed
        ReportUI reportUI = new ReportUI();
        jPanelLoader.JPanelLoader(panelLoader, reportUI);
    }//GEN-LAST:event_showReportsButtonActionPerformed

    private void exportImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportImportButtonActionPerformed
        ImportExportUI importExportUI = new ImportExportUI();
        jPanelLoader.JPanelLoader(panelLoader, importExportUI);
    }//GEN-LAST:event_exportImportButtonActionPerformed

    private void showUserInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserInfoButtonActionPerformed
        UserInfo userInfo = new UserInfo();
        userInfo.setLocationRelativeTo(null);
        userInfo.setVisible(true);
    }//GEN-LAST:event_showUserInfoButtonActionPerformed

    private void terminateSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminateSessionButtonActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to terminate the session?",
                "Terminate Session",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
            DbConnection.closeConnection();
            new LoginUI().setVisible(true);
        }
    }//GEN-LAST:event_terminateSessionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dbConnectionShowStatusLabel;
    private javax.swing.JLabel dbConnectionStatusLabel;
    private javax.swing.JToggleButton exportImportButton;
    private javax.swing.JPanel panelLoader;
    private javax.swing.JToggleButton showInvoiceButton;
    private javax.swing.JToggleButton showProductsButton;
    private javax.swing.JToggleButton showReportsButton;
    private javax.swing.JToggleButton showSalesButton;
    private javax.swing.JButton showUserInfoButton;
    private javax.swing.JToggleButton showUsersButton;
    private javax.swing.ButtonGroup sideBarButtonGroup;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton terminateSessionButton;
    // End of variables declaration//GEN-END:variables
}
