/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hridaya.tickbill.view;

import com.hridaya.tickbill.database.DbConnection;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;

/**
 *
 * @author hridaya
 */
public class ProductUI extends javax.swing.JPanel {

    /**
     * Creates new form UserUI
     */
    public ProductUI() {
        initComponents();
        productLoad();
    }

    private void productLoad() {
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        dtm.setRowCount(0);

        String sql = "SELECT * FROM inventory";
        try (Statement st = DbConnection.getConnection().createStatement(); ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getInt("product_id"));
                row.add(rs.getString("product_name"));
                row.add(rs.getDouble("product_rate"));
                row.add(rs.getInt("product_quantity"));
                dtm.addRow(row);
            }
        } catch (SQLException e) {
            Utils.showError("Error loading products", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        productSaveButton = new javax.swing.JButton();
        productNameLabel = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        productQuantityTextField = new javax.swing.JTextField();
        productDeleteButton = new javax.swing.JButton();
        productSearchButton = new javax.swing.JButton();
        productUpdateButton = new javax.swing.JButton();
        productIdTextField = new javax.swing.JTextField();
        productNameTextField = new javax.swing.JTextField();
        productPriceTextField = new javax.swing.JTextField();
        productQuantityLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1506, 4));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        productSaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productSaveButton.setText("Create");
        productSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSaveButtonActionPerformed(evt);
            }
        });

        productNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productNameLabel.setText("Name:");

        userIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userIdLabel.setText("Search ID:");

        productPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productPriceLabel.setText("Price:");

        productDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productDeleteButton.setText("Delete");
        productDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDeleteButtonActionPerformed(evt);
            }
        });

        productSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productSearchButton.setText("Search");
        productSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSearchButtonActionPerformed(evt);
            }
        });

        productUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productUpdateButton.setText("Update");
        productUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUpdateButtonActionPerformed(evt);
            }
        });

        productQuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productQuantityLabel.setText("Quantity:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(productSaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(productSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(productUpdateButton)
                        .addGap(18, 18, 18)
                        .addComponent(productDeleteButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(productPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productQuantityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productIdTextField)
                            .addComponent(productNameTextField)
                            .addComponent(productPriceTextField)
                            .addComponent(productQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdLabel)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPriceLabel)
                    .addComponent(productPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productQuantityLabel)
                    .addComponent(productQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSaveButton)
                    .addComponent(productSearchButton)
                    .addComponent(productUpdateButton)
                    .addComponent(productDeleteButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSaveButtonActionPerformed
        String productName = productNameTextField.getText();
        double productPrice = Utils.parseDoubleField(productPriceTextField);
        int productQuantity = Utils.parseIntField(productQuantityTextField);

        String sql = "INSERT INTO inventory(product_name, product_rate, product_quantity) VALUES ('" + productName + "', " + productPrice + ", " + productQuantity + ")";
        Utils.executeUpdate(sql, "Product created successfully!");
        productLoad();
    }//GEN-LAST:event_productSaveButtonActionPerformed

    private void productUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUpdateButtonActionPerformed
        String productId = productIdTextField.getText();
        String productName = productNameTextField.getText();
        double productPrice = Utils.parseDoubleField(productPriceTextField);
        int productQuantity = Utils.parseIntField(productQuantityTextField);

        String sql = "UPDATE inventory SET product_name = '" + productName + "', product_rate = " + productPrice
                + ", product_quantity = " + productQuantity + " WHERE product_id = '" + productId + "'";
        Utils.executeUpdate(sql, "Product updated successfully!");
        productLoad();
    }//GEN-LAST:event_productUpdateButtonActionPerformed

    private void productSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSearchButtonActionPerformed
        String productId = productIdTextField.getText();
        String sql = "SELECT product_name, product_rate, product_quantity FROM inventory WHERE product_id = '" + productId + "'";

        try (Statement st = DbConnection.getConnection().createStatement(); ResultSet rs = st.executeQuery(sql)) {

            if (rs.next()) {
                productNameTextField.setText(rs.getString("product_name,"));
                productPriceTextField.setText(String.valueOf(rs.getDouble("product_rate")));
                productQuantityTextField.setText(String.valueOf(rs.getInt("product_quantity")));
            } else {
                Utils.showInfo("Product not found");
            }
        } catch (SQLException e) {
            Utils.showError("Error searching product", e);
        }
    }//GEN-LAST:event_productSearchButtonActionPerformed

    private void productDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDeleteButtonActionPerformed
        String productId = productIdTextField.getText();
        String sql = "DELETE FROM inventory WHERE product_id = '" + productId + "'";
        Utils.executeUpdate(sql, "Product deleted successfully!");
        productLoad();
    }//GEN-LAST:event_productDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton productDeleteButton;
    private javax.swing.JTextField productIdTextField;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JTextField productPriceTextField;
    private javax.swing.JLabel productQuantityLabel;
    private javax.swing.JTextField productQuantityTextField;
    private javax.swing.JButton productSaveButton;
    private javax.swing.JButton productSearchButton;
    private javax.swing.JTable productTable;
    private javax.swing.JButton productUpdateButton;
    private javax.swing.JLabel userIdLabel;
    // End of variables declaration//GEN-END:variables
}
