/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hridaya.tickbill.view;

import com.hridaya.tickbill.database.DbConnection;

import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;

/**
 *
 * @author hridaya
 */
public class ProductUI extends javax.swing.JPanel {

    /**
     * Creates new form UserUI
     */
    public ProductUI() {
        initComponents();
        productLoad();
    }

    private String cachedProductId;

    private void productLoad() {
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        dtm.setRowCount(0);

        String sql = "SELECT * FROM inventory";
        try (Statement st = DbConnection.getConnection().createStatement(); ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getInt("product_id"));
                row.add(rs.getString("product_name"));
                row.add(rs.getDouble("product_rate"));
                row.add(rs.getInt("product_quantity"));
                dtm.addRow(row);
            }
        } catch (SQLException e) {
            Utils.showError("Error loading products", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        productQuantityTextField = new javax.swing.JTextField();
        productNameTextField = new javax.swing.JTextField();
        productPriceTextField = new javax.swing.JTextField();
        productQuantityLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        productUpdateButton = new javax.swing.JButton();
        productDeleteButton = new javax.swing.JButton();
        productSearchButton = new javax.swing.JButton();
        productSaveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(1300, 680));
        setMinimumSize(new java.awt.Dimension(1300, 680));
        setPreferredSize(new java.awt.Dimension(1300, 680));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ));
        productTable.setShowGrid(true);
        jScrollPane2.setViewportView(productTable);

        productNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productNameLabel.setText("Name:");

        productPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productPriceLabel.setText("Price:");

        productQuantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productQuantityLabel.setText("Quantity:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(productPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productQuantityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPriceLabel)
                    .addComponent(productPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productQuantityLabel)
                    .addComponent(productQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productUpdateButton.setText("Update");
        productUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUpdateButtonActionPerformed(evt);
            }
        });

        productDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productDeleteButton.setText("Delete");
        productDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDeleteButtonActionPerformed(evt);
            }
        });

        productSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productSearchButton.setText("Search");
        productSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSearchButtonActionPerformed(evt);
            }
        });

        productSaveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productSaveButton.setText("Create");
        productSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(172, 172, 172));
        jSeparator1.setForeground(new java.awt.Color(172, 172, 172));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSaveButtonActionPerformed
        String productName = productNameTextField.getText();
        String productPrice = productPriceTextField.getText();
        String productQuantity = productQuantityTextField.getText();

        if (productName.isEmpty() || productPrice.isEmpty() || productQuantity.isEmpty()) {
            Utils.showError("Provide valid input");
            return;
        }

        String sql = "INSERT INTO inventory(product_name, product_rate, product_quantity) VALUES ('" + productName + "', " + productPrice + ", " + productQuantity + ")";
        try {
            Statement st = DbConnection.getConnection().createStatement();
            st.executeUpdate(sql);
            st.close();
        } catch (SQLException ex) {
            Utils.showError(ex.getMessage());
        }
        productLoad();
    }//GEN-LAST:event_productSaveButtonActionPerformed

    private void productUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUpdateButtonActionPerformed
        String productName = productNameTextField.getText();
        String productPrice = productPriceTextField.getText();
        String productQuantity = productQuantityTextField.getText();

        if (productName.isEmpty()) {
            Utils.showError("Provide product name.");
            return;
        }

        if (productPrice.isEmpty() || productQuantity.isEmpty()) {
            Utils.showError("Provide valid input");
            return;
        }

        String updateSql = "UPDATE inventory SET product_name = ?, product_rate = ?, product_quantity = ? WHERE product_id = ?";

        if (cachedProductId != null) {
            try (PreparedStatement psUpdate = DbConnection.getConnection().prepareStatement(updateSql)) {

                psUpdate.setString(1, productName);
                psUpdate.setDouble(2, Double.parseDouble(productPrice));
                psUpdate.setInt(3, Integer.parseInt(productQuantity));
                psUpdate.setString(4, cachedProductId);

                psUpdate.executeUpdate();
            } catch (SQLException ex) {
                Utils.showError(ex.getMessage());
            }
        }

        productLoad();
    }//GEN-LAST:event_productUpdateButtonActionPerformed

    private void productSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSearchButtonActionPerformed
        String productName = productNameTextField.getText();
        String sql = "SELECT product_name, product_rate, product_quantity FROM inventory WHERE product_name = ?";

        if (productName.isEmpty()) {
            Utils.showError("Provide product name");
            return;
        }

        String querySql = "SELECT product_id FROM inventory WHERE product_name = ?";
        try (PreparedStatement psSelect = DbConnection.getConnection().prepareStatement(querySql)) {

            psSelect.setString(1, productName);
            ResultSet rs = psSelect.executeQuery();

            if (rs.next()) {
                cachedProductId = rs.getString("product_id");
            } else {
                Utils.showError("Product not found.");
                return;
            }
        } catch (SQLException ex) {
            Utils.showError(ex.getMessage());
            return;
        }

        try (PreparedStatement st = DbConnection.getConnection().prepareStatement(sql)) {
            st.setString(1, productName);
            try (ResultSet rs = st.executeQuery()) {
                if (rs.next()) {
                    productNameTextField.setText(rs.getString("product_name"));
                    productPriceTextField.setText(String.valueOf(rs.getDouble("product_rate")));
                    productQuantityTextField.setText(String.valueOf(rs.getInt("product_quantity")));
                } else {
                    Utils.showInfo("Product not found");
                }
            }
        } catch (SQLException ex) {
            Utils.showError(ex.getMessage());
        }
    }//GEN-LAST:event_productSearchButtonActionPerformed

    private void productDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDeleteButtonActionPerformed
        String productName = productNameTextField.getText();

        if (productName.isEmpty()) {
            Utils.showError("Product ID is empty");
            return;
        }

        String sql = "DELETE FROM inventory WHERE product_name = ?";
        try (PreparedStatement st = DbConnection.getConnection().prepareStatement(sql)){
            st.setString(1, productName);
            st.executeUpdate();
        } catch (SQLException e) {
            Utils.showError("Error deleting product", e);
        }
        productLoad();
    }//GEN-LAST:event_productDeleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton productDeleteButton;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JTextField productPriceTextField;
    private javax.swing.JLabel productQuantityLabel;
    private javax.swing.JTextField productQuantityTextField;
    private javax.swing.JButton productSaveButton;
    private javax.swing.JButton productSearchButton;
    private javax.swing.JTable productTable;
    private javax.swing.JButton productUpdateButton;
    // End of variables declaration//GEN-END:variables
}
